Support new oconfigure parameters.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -140,27 +140,27 @@ ismanual() {
 
 singletest() {
 	cat 1>&3 << __HEREDOC__
-${1}${3}: testing...
-${COMP} -o test-${1} test-${1}.c ${3}
+${1}: testing...
+${COMP} ${3} -o test-${1} test-${1}.c
 __HEREDOC__
 
-	if ${COMP} -o "test-${1}" "test-${1}.c" ${3} 1>&3 2>&3; then
-		echo "${1}${3}: ${CC} succeeded" 1>&3
+	if ${COMP} ${3} -o "test-${1}" "test-${1}.c" 1>&3 2>&3; then
+		echo "${1}: ${CC} succeeded" 1>&3
 	else
-		echo "${1}${3}: ${CC} failed with $?" 1>&3
+		echo "${1}: ${CC} failed with $?" 1>&3
 		echo 1>&3
 		return 1
 	fi
 
 	if ./test-${1} 1>&3 2>&3; then
-		echo "${1}${3}: yes" 1>&2
-		echo "${1}${3}: yes" 1>&3
+		echo "${1}: yes" 1>&2
+		echo "${1}: yes" 1>&3
 		echo 1>&3
 		eval HAVE_${2}=1
 		rm "test-${1}"
 		return 0
 	else
-		echo "${1}${3}: execution failed with $?" 1>&3
+		echo "${1}: execution failed with $?" 1>&3
 		echo 1>&3
 		rm "test-${1}"
 		return 1
@@ -176,12 +176,12 @@ runtest() {
 	ismanual "${1}" "${2}" "${_manual}" && return 0
 	if [ ! -r "test-${1}.c" ]
 	then
-		echo "${1}${3}: skipping (no test file)" 1>&2
+		echo "${1}: skipping (no test file)" 1>&2
 		eval HAVE_${2}=0
 		return 1
 	fi
 	singletest "${1}" "${2}" "${3}" && return 0
-	echo "${1}${3}: no" 1>&2
+	echo "${1}: no" 1>&2
 	eval HAVE_${2}=0
 	return 1
 }
@@ -193,15 +193,15 @@ runtest() {
 # You WANT to change this.
 #----------------------------------------------------------------------
 
-runtest err		ERR		|| true
-runtest PATH_MAX	PATH_MAX	|| true
-runtest pledge		PLEDGE		|| true
-runtest progname	PROGNAME	|| true
-runtest reallocarray	REALLOCARRAY	|| true
-runtest sandbox_init	SANDBOX_INIT	|| true
-runtest strlcat		STRLCAT		|| true
-runtest strlcpy		STRLCPY		|| true
-runtest strtonum	STRTONUM	|| true
+runtest err		ERR				  || true
+runtest PATH_MAX	PATH_MAX			  || true
+runtest pledge		PLEDGE				  || true
+runtest progname	PROGNAME			  || true
+runtest reallocarray	REALLOCARRAY			  || true
+runtest sandbox_init	SANDBOX_INIT	"-Wno-deprecated" || true
+runtest strlcat		STRLCAT				  || true
+runtest strlcpy		STRLCPY				  || true
+runtest strtonum	STRTONUM			  || true
 
 #----------------------------------------------------------------------
 # Output writing: generate the config.h file.
